Module: Add server module
bluerobotics/MAVProxy pull request #3
Opened 2018-05-04 18:28 UTC by patrickelectric

Add json and rest servers

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2018-05-04 18:40 UTC, patrickelectric commented
Just opening a review here before creating one in the original repository.

2018-05-04 19:30 UTC, jaxxzer commented on MAVProxy/modules/mavproxy_server.py
> +        '''We don't have time to wast'''
sp. waste

2018-05-04 21:19 UTC, jaxxzer commented
This doesn't show up in `module list` output. Neither do depthoutput or gpsinput for that matter.

2018-05-04 22:13 UTC, patrickelectric commented
Are you running it on source or have you installed it ?
You can use this patch https://github.com/ArduPilot/MAVProxy/pull/504 to run without installing.

2018-07-30 21:29 UTC, jaxxzer requested changes
For the jsonserver, Instead of requesting a specific message at a certain interval (this isn't even supported yet in the mavlink api), we should request a specific message, and push the messages out as soon as they are received from the autopilot. This can be done by hooking into (mavlink_packet)[https://github.com/bluerobotics/MAVProxy/blob/master/MAVProxy/modules/mavproxy_DepthOutput.py#L39]

This way updates are only pushed when there is new data, and as soon as it is available.

2019-11-05 14:00 UTC, closed without merging

2019-11-08 04:08 UTC, jaxxzer commented
:cry: